image: alpine

variables:
  GIT_SUBMODULE_STRATEGY: recursive
pages:
  script:
  - apk update && apk add doxygen
  - doxygen Doxyfile
  - mv docs/html/ public/
  artifacts:
    paths:
    - public
  only:
  - main