
doc:
  stage: build
  image: alpine
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - apk update && apk add doxygen
  - doxygen Doxyfile
  artifacts:
    paths:
    - docs
  only:
  - main

pages:
  stage: deploy
  script:
  - mv docs/html/ public/
  artifacts:
    paths:
    - public