
linux:
  stage: build
  image: python:3.12
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install cibuildwheel==2.22.0
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/

doc:
  stage: build
  image: alpine
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - apk update && apk add doxygen
  - doxygen Doxyfile
  artifacts:
    paths:
    - docs
  only:
  - main

pages:
  stage: deploy
  script:
  - mv docs/html/ public/
  artifacts:
    paths:
    - public