name: build wheels

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_wheels:
    name: build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: build wheels
        uses: pypa/cibuildwheel@v2.23.2

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

          

